# "데이터 분석 numpy 기초 문법 노트북"

> "2021년 여름방학 데이터분석을 위한 numpy 기초문법"

- toc:true
- branch: master
- badges: true
- comments: true
- author: OH CHUNGHYEON
- categories: [python, 데이터분석, numpy]

In [4]:
리스트 = [[1,2,3], [4, 5, 6], [7, 8, 9]]
리스트[0][0]
리스트[0]
리스트[2][0]

리스트*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
import numpy as np

리스트 = [[1,2,3], [4, 5, 6], [7, 8, 9]]
리스트 = np.array(리스트)

리스트 * 2
리스트 + 100


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [10]:
a = np.arange(15).reshape(3, 5) #arange에서 0~14까지 나열하고, 3열5줄로 재형성하는 코드임.

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a = np.arange(20).reshape(2, 2, 5) #arange에서 0~14까지 나열하고, 3열5줄로 재형성하는 코드임.

a

a[0]
a[0][0]
a[0][0][3]

a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [27]:
a = np.arange(15).reshape(3, 5)

a
a.shape       # 행렬 개수
a.ndim        # 차원의 개수
a.dtype.name  # 데이터 넓이?? 크기?? 2진수ㄷㄷ
a.itemsize    # 거의 볼 일 없음...
a.size        # flat한 데이터 사이즈 
type(a)       # a의 타입


numpy.ndarray

In [29]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((2, 3), dtype=np.int16)


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [34]:
np.empty((2, 3))  # 0에 충분히 가까운 자연수 값을 부름

array([[4.68832883e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [36]:
np.arange(0, 2, 0.3)  # 0부터 2까지 0.3 간격으로 나열

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [38]:
np.linspace(0, 2, 9)  # 0부터2까지 9개 숫자를 같은 간격으로 나열

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
rg = np.random.default_rng(1)


In [40]:
a = rg.random((2, 3))

a

a.sum()
a.min()
a.max()


0.9504636963259353

In [42]:
리스트 = [[1,2,3], [4, 5, 6], [7, 8, 9]]

a = np.array(리스트)

a.sum()
a.min()
a.max()


9

In [47]:
리스트 = [[10,2,3], [4, 5, 6], [7, 8, 9]]

a = np.array(리스트)

a.sum()               # sum(리스트)는 애러납니다
a.min(), min(리스트)
a.max(), max(리스트)  # max(리스트)는 각각의 행에서 맨앞의 수를 비교해서 제일 큰 행을 출력함   

(10, [10, 2, 3])

In [49]:
b = np.arange(12).reshape(3, 4)

b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
#행렬에서의 더하기 기능이 다양하게 이루어짐

b.sum(axis=0)   # 열(col)기준으로 행(row)끼리 더한 것
b.sum(axis=1) # 행(row)기준으로 열(col)끼리 더한 것
# b.sum()       # flat하게(모든 요소를) 모두 더한 것




array([ 6, 22, 38])

In [56]:
b.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
b.transpose()   #잘 안씀
b.T             #잘 씀!!! 행과 열을 바꿔줌. (3,4) -> (4,3)이면서...숫자도 세로로...

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [67]:
a = np.array([[1, 2], [3, 4]])
b = np.floor([[5, 6], [7, 8]])
np.vstack((a, b))
np.hstack((a, b))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [65]:
#매우 많이 사용되는 것임
a = np.arange(12).reshape(3, 4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
b.sum()

7